export const TASK_COMPLETED = 'TASK_COMPLETED';
export const REMOVE_COMPLETED_TASK = 'REMOVE_COMPLETED_TASK';
export const REMOVE_INCOMPLETE_TASK = 'REMOVE_INCOMPLETE_TASK';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
